alias vim="nvim"
alias c="clear && echo -ne '\e[5 q'"
alias clear="clear && echo -ne '\e[5 q'"
alias cl="clear && echo -ne '\e[5 q'"
alias ra="ranger"
alias ls=lsd
alias ll="lsd -l"
alias lg="lazygit"
alias t=tmux
alias e=exit
